name: Build on push/release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:

  build_studio:
    name: Build studio
    runs-on: ubuntu-20.04
    outputs:
      image: ${{ steps.meta.outputs.json }}
    permissions:
      packages: write
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/scaleoutsystems/power-consumption
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      - name: Buildx driver
        run: |
          docker buildx create --use --driver=docker-container
        
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push studio
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
